apiVersion: v1
kind: Service
metadata:
  name: capstone
  labels:
    name: capstone
    version: "BUILD"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    name: capstone
    version: "BUILD"