apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-BUILD
spec:
  selector:
    matchLabels:
      name: capstone
      version: "BUILD"
  replicas: 2
  template:
    metadata:
      labels:
        name: capstone
        version: "BUILD"
    spec:
      containers:
      - name: capstone
        image: anorum/udacitycapstone:BUILD
        imagePullPolicy: Always
        ports:
        - containerPort: 80