---
    - name: "update apt packages"
      become: yes
      apt:
        update_cache: yes
    - name: "upgrade packages"
      become: yes
      apt:
        upgrade: yes
    - name: "Install EKSCTL and create cluster"
      become: yes
      shell: |
        curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/0.23.0/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
        sudo mv /tmp/eksctl /usr/local/bin
        eksctl create cluster -f /tmp/cluster.yml